name: terminal

on:
  workflow_dispatch:

permissions:
  contents: write  # Permet au workflow de pousser du code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Your step here
        run: |
          # vos commandes
          
      - name: Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update from workflow"
          git push
